import { type Template } from "./index";

const solidEditor: Template = {
  // index: 2,
  title: "Solid editor background",
  // title: "Solid editor background (variant 1)",
  alpha: 70,
  colors: [
    {
      type: "colors",
      name: "primary",
      properties: [
        { name: "editor.background" },
        { name: "editorGutter.background" },
        { name: "activityBar.activeBackground" },
        { name: "editorCursor.background" },
        { name: "editorGroupHeader.tabsBackground" },
        { name: "list.activeSelectionBackground" },
        { name: "list.inactiveSelectionBackground" },
        { name: "statusBar.background" },
        { name: "statusBar.noFolderBackground" },
        { name: "tab.activeBackground" },
      ],
      defaultDark: "#1c1e26",
      defaultLight: "#f3f1e9",
    },
    {
      // optional: true,
      type: "colors",
      name: "secondary",
      properties: [
        { name: "activityBar.background" },
        { name: "terminal.background" },
        { name: "sideBar.background" },
        { name: "panel.background" },
        { name: "sideBarSectionHeader.background" },
        { name: "tab.inactiveBackground" },
        { name: "titleBar.activeBackground" },
        { name: "titleBar.inactiveBackground" },
      ],
      defaultDark: "#20232b",
      defaultLight: "#e4e4d7",
    },
    {
      type: "colors",
      name: "tertiary",
      properties: [
        { name: "breadcrumbPicker.background" },
        { name: "dropdown.background" },
        { name: "editorWidget.background" },
        { name: "editorWidget.border" },
        { name: "peekViewEditor.background" },
        { name: "peekViewResult.background" },
        { name: "peekViewTitle.background" },
        { name: "walkThrough.embeddedEditorBackground" },
      ],
      defaultDark: "#232530",
      defaultLight: "#fafae1",
    },
    {
      type: "colors",
      name: "lists and inputs",
      // name: "lists, buttons and inputs",
      properties: [
        { name: "walkThrough.embeddedEditorBackground" },
        //{ name: "button.background" },
        { name: "dropdown.listBackground" },
        { name: "editorIndentGuide.activeBackground1" },
        { name: "editorIndentGuide.background1", isTransparent: true },
        { name: "editorOverviewRuler.border", isTransparent: true },
        { name: "input.background" },
        { name: "list.hoverBackground", isTransparent: true },
        { name: "peekViewResult.selectionBackground", isTransparent: true },
        { name: "statusBarItem.hoverBackground" },
        { name: "statusBarItem.prominentBackground" },
      ],
      defaultDark: "#2e303e",
      defaultLight: "#d2d0c8",
    },
  ],
};
export default solidEditor;
