import { type Template } from "./index";

const terminalColors: Template = {
  title: "Terminal",
  colors: [
    {
      type: "colors",
      name: "black",
      properties: [{ name: "terminal.ansiBlack" }],
      optional: true,
      defaultDark: "#42444D",
      defaultLight: "#42444D",
    },
    {
      type: "colors",
      name: "bright black",
      properties: [{ name: "terminal.ansiBrightBlack" }],
      optional: true,
      defaultDark: "#8F9AAE",
      defaultLight: "#57606A",
    },
    {
      type: "colors",
      name: "white",
      properties: [{ name: "terminal.ansiWhite" }],
      optional: true,
      defaultDark: "#CDD3E0",
      defaultLight: "#6E7781",
    },
    {
      type: "colors",
      name: "bright white",
      properties: [{ name: "terminal.ansiBrightWhite" }],
      optional: true,
      defaultDark: "#FFFFFF",
      defaultLight: "#8C959F",
    },
    {
      type: "colors",
      name: "red",
      properties: [{ name: "terminal.ansiRed" }],
      optional: true,
      defaultDark: "#FC2E51",
      defaultLight: "#CF222E",
    },
    {
      type: "colors",
      name: "bright red",
      properties: [{ name: "terminal.ansiBrightRed" }],
      optional: true,
      defaultDark: "#FF608C",
      defaultLight: "#A40E26",
    },
    {
      type: "colors",
      name: "green",
      properties: [{ name: "terminal.ansiGreen" }],
      optional: true,
      defaultDark: "#25A45C",
      defaultLight: "#116329",
    },
    {
      type: "colors",
      name: "bright green",
      properties: [{ name: "terminal.ansiBrightGreen" }],
      optional: true,
      defaultDark: "#3FC56A",
      defaultLight: "#1A7F37",
    },
    {
      type: "colors",
      name: "blue",
      properties: [{ name: "terminal.ansiBlue" }],
      optional: true,
      defaultDark: "#3375FE",
      defaultLight: "#0969DA",
    },
    {
      type: "colors",
      name: "bright blue",
      properties: [{ name: "terminal.ansiBrightBlue" }],
      optional: true,
      defaultDark: "#10B0FE",
      defaultLight: "#218BFF",
    },
    {
      type: "colors",
      name: "yellow",
      properties: [{ name: "terminal.ansiYellow" }],
      optional: true,
      defaultDark: "#FFCB69",
      defaultLight: "#d6aa09",
    },
    {
      type: "colors",
      name: "bright yellow",
      properties: [{ name: "terminal.ansiBrightYellow" }],
      optional: true,
      defaultDark: "#eef958",
      defaultLight: "#F9C858",
    },
    {
      type: "colors",
      name: "magenta",
      properties: [{ name: "terminal.ansiMagenta" }],
      optional: true,
      defaultDark: "#B183FF",
      defaultLight: "#8250DF",
    },
    {
      type: "colors",
      name: "bright magenta",
      properties: [{ name: "terminal.ansiBrightMagenta" }],
      optional: true,
      defaultDark: "#FF78F8",
      defaultLight: "#A475F9",
    },
    {
      type: "colors",
      name: "cyan",
      properties: [{ name: "terminal.ansiCyan" }],
      optional: true,
      defaultDark: "#4483AA",
      defaultLight: "#1B7C83",
    },
    {
      type: "colors",
      name: "bright cyan",
      properties: [{ name: "terminal.ansiBrightCyan" }],
      optional: true,
      defaultDark: "#5FB9BC",
      defaultLight: "#3192AA",
    },
  ],
};

export default terminalColors;
